---
language: python
services:
  - docker
cache: pip

env:
  global:
    - ANSIBLE_ROLE: quantum_espresso

matrix:
  include:
    - name: Ubuntu-18.04
      env:
        - DOCKER_IMAGE: marvelnccr/ubuntu-docker-base
        - DOCKER_IMAGE_VERSION: 2.2
        - ANSIBLE_USER: ubuntu
    - name: Ubuntu-16.04
      env:
        - DOCKER_IMAGE: marvelnccr/ubuntu-docker-base
        - DOCKER_IMAGE_VERSION: 1.1
        - ANSIBLE_USER: ubuntu


install:
# Upgrade pip setuptools and wheel
- pip install -U pip wheel setuptools
- pip install cookiecutter
- cookiecutter --no-input .
- pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - mv ansible-role-$ANSIBLE_ROLE marvel-nccr.$ANSIBLE_ROLE
  - cd marvel-nccr.$ANSIBLE_ROLE

script:
  - molecule test
